config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users
  
  resources :projects do
    resources :tasks
  end
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
 
  def overdue_counter 
    overdue_tasks = tasks.select do |task|
      task.complete.blank? && task.due < Date.today
    end
    return overdue_tasks.count
  end

  def counter 
    tasks.all.count
  end

  def completion_counter
    counter - overdue_counter
  end

  def percentage
    if counter != 0
      "#{((completion_counter.to_f / counter.to_f) * 100.0).to_i}%" 
    else
      "0%"
    end
  end


end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  def complete_test
    if complete?
      "Complete"
    elsif due < Date.today && complete? == false
      "Overdue"
    end
  end

  def overdue_calculator
    if complete?
      false
    else
      due < Date.today
    end
  end

  def class_selecter
    if complete_test == "Complete"
      "badge text-bg-success"
    elsif complete_test == "Overdue"
      "badge text-bg-danger"
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/custom_devise_controller.rb
class CustomDeviseController < ApplicationController

  layout "authentication"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = @project.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = @project.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_task_url(@project, @task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_task_url(@project, @task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to project_tasks_url(@project), notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_project 
      @project = Project.find(params[:project_id])
    end

    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :due, :complete, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_devise_helper.rb
module CustomDeviseHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Completion (percentage of tasks complete)</th>
      <th>Overdue Tasks (count)</th>
    </tr>
  </thead>
  <tbody>
    <% Project.all.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= project.percentage %></td>
        <td><%= project.overdue_counter  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-bs-theme="dark">
  <head>
    <title>ProjectManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Project Management</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <% if current_user.present? %>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/projects">Projects</a>
            </li>
          </ul>
        </div>

        <%= button_to("Sign Out", destroy_user_session_path, :method => :delete, :class => "btn btn-outline-secondary") %>
      <% end %>
    </div>
    </nav>

    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html data-bs-theme="dark">
  <head>
    <title>ProjectManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Project Management</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <% if current_user.present? %>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/projects">Projects</a>
            </li>
          </ul>
        </div>

        <%= button_to("Sign Out", destroy_user_session_path, :method => :delete, :class => "btn btn-outline-secondary") %>
      <% end %>
    </div>
    </nav>

    <div class="container">
      <div id="authentic" class="card">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for project do |form| %>

  <%= form.input :name %>

  <div>
    <%= form.input :description %>
  </div>

  <div>
    <%= form.button :submit, :class => "btn btn-primary"  %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Project</li>
  </ol>
</nav>

<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <div class="card mt-3">
      <%= render project %>
      <p>
      <%= link_to "Show this project", project %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Projects", projects_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @project.name %></li>
  </ol>
</nav>

<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %> |
  <%= link_to "Tasks", project_tasks_path(@project) %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for([@project, @task]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :due %>
    <%= f.input :complete %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Name:</strong>
    <%= task.name %>
  </p>

  <p>
    <strong>Due:</strong>
    <%= task.due %>
  </p>

  <p>
    <strong>Complete:</strong>
    <%= task.complete %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= task.project_id %>
  </p>

</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", project_task_path(@project, @task) %> |
  <%= link_to "Back to tasks", project_tasks_path(@project) %>
</div>

app/views/tasks/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Projects", projects_path %></li>
    <li class="breadcrumb-item"><%= link_to @project.name, project_path(@project) %></li>
    <li class="breadcrumb-item active" aria-current="page">Tasks</li>
  </ol>
</nav>


<p style="color: green"><%= notice %></p>

<h1><%= @project.name %> - Tasks</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>name</th>
      <th>Due Date</th>
      <th>Complete</th>
      <th>Overdue</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.name, project_task_path(@project, task) %></td>
        <td><%= task.due %></td>
        <td><%= task.complete %></td>
        <td><%= task.overdue_calculator %></td>
        <td><span class="<%= task.class_selecter %>"><%= task.complete_test %></span></td>
      </tr>
    <% end %>
  </tbody>
</table>










<!--<div id="tasks">
 <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", project_task_path(@project, task) %>
    </p>
  <% end %>
</div> -->

<%= link_to "New task", new_project_task_path(@project) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", project_tasks_path(@project) %>
</div>

app/views/tasks/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Projects", projects_path %></li>
    <li class="breadcrumb-item"><%= link_to @project.name, project_path(@project) %></li>
    <li class="breadcrumb-item"><%= link_to "Tasks", project_tasks_path(@project) %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @task.name %></li>
  </ol>
</nav>

<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_project_task_path(@project, @task) %> |
  <%= link_to "Back to tasks", project_tasks_path(@project) %>

  <%= button_to "Destroy this task", project_task_path(@project, @task), method: :delete %>
</div>